Import('env')

objs = [env.Object(Glob('*.cpp')),
        SConscript('common/SConscript'),
        SConscript('math/SConscript'),
        SConscript('plot/SConscript'),
        SConscript('examples/SConscript')]

Return('objs')
