# Please refer the DockerREADME.md file 
# for the details regarding this docker-compose file

version: "3.3"

networks:
  default:
    driver: overlay
    attachable: true
  front-tier:
  back-tier:
    attachable: true

services:
  anemocppserver:
    image: anemomind/anemomind_anemocppserver:${TAG:-latest}
    volumes:
      - "./www2/uploads:/db/uploads"
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
      - MONGO_URL=mongodb://anemomongo/anemomind-dev
    
    command: /anemomind/bin/run_from_cron.sh
    links:
      - anemomongo
    depends_on:
      - anemomongo

  anemowebapp:
    image: anemomind/web_dev:${TAG:-latest}
    ports:
      - "9001:9001"
      - "35729:35729"
    volumes: 
      - "./nodemodules:/anemomind/nodemodules"
      - "./www2:/anemomind/www2"
      - "./datasets:/anemomind/datasets"
      - "/tmp/home:/home"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped
    command: ./grunt.sh serve:dev
    environment:
      - PORT=9001
      - WAIT_HOSTS=anemomongo:27017
      - MONGO_URL=mongodb://anemomongo/anemomind-dev
      - JWT_SECRET=${JWT_SECRET:-NOT_SECURE_AT_ALL_123}
      - USE_GS=false  # store on filesystem
      - SKIP_OPEN_BROWSER=1
      - HOME=/home
      - LD_LIBRARY_PATH=/anemomind/lib

    user: ${USER_ID}
    links:
      - anemomongo
    depends_on:
      - anemomongo
      - anemocppserver

  anemomongo:
    image: mongo:4.2.5-bionic
    container_name: anemomongo
    volumes:
      - "db-data:/data/db"
    ports:
      - "27017:27017"
    networks:
      - back-tier
    restart: unless-stopped

volumes:
    boat_logs:
    db-data:

