# Please refer the DockerREADME.md file 
# for the details regarding this docker-compose file

version: "3.3"

services:
  anemocppserver:
    image: anemomind/anemomind_anemocppserver:${TAG:-latest}
    volumes:
      - "file-db:/db"
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
    
    links:
      - anemomongo
    depends_on:
      - anemomongo

  anemowebapp:
    image: anemomind/anemomind_anemowebapp:${TAG:-latest}
    ports:
      - "9000:80"
    volumes: 
      - "file-db:/db"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
      - MONGOLAB_URI=mongodb://anemomongo/anemomind
      - JWT_SECRET=${JWT_SECRET:-NOT_SECURE_AT_ALL_123}
    
    links:
      - anemomongo
    depends_on:
      - anemomongo
      - anemocppserver

  anemomongo:
    image: mvertes/alpine-mongo
    container_name: anemomongo
    volumes:
      - "db-data:/db/data"
    ports:
      - "27017:27017"
    networks:
      - back-tier
    restart: unless-stopped

volumes:
    boat_logs:
    db-data:
    file-db:

networks:
  front-tier:
  back-tier:
    attachable: true
