# Please refer the DockerREADME.md file 
# for the details regarding this docker-compose file

version: "3.3"

services:
  anemocppserver:
    image: anemomind/anemomind_anemocppserver:${TAG:-latest}
    volumes:
      - "file-db:/db"
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
      - MONGO_URL=mongodb://anemomongo/anemomind
    
    command: /anemomind/bin/run_from_cron.sh
    links:
      - anemomongo
    depends_on:
      - anemomongo

  anemowebapp:
    image: anemomind/anemomind_anemowebapp:${TAG:-latest}
    #ports:
    #- "9000:9000"
    volumes: 
      - "file-db:/db"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped
    environment:
      - PORT=9000
      - WAIT_HOSTS=anemomongo:27017
      - MONGOLAB_URI=mongodb://anemomongo/anemomind
      - JWT_SECRET=${JWT_SECRET:-NOT_SECURE_AT_ALL_123}
      - USE_GS=false  # store on filesystem
    
    links:
      - anemomongo
    depends_on:
      - anemomongo
      - anemocppserver
    labels:
      - traefik.enable=true
      - traefik.http.routers.anemowebapp.rule=Host(`anemolab.com`) || Host(`www.anemolab.com`)
      #- traefik.http.routers.anemowebapp.service=anemowebapp
      - traefik.http.routers.anemowebapp.entrypoints=websecure
      - traefik.http.routers.anemowebapp.tls.certresolver=le
      - traefik.http.services.anemowebapp.loadbalancer.server.port=9000
      - traefik.docker.network=anemolab_net

  # This can be scaled. Nginx, started with docker-compose-nginx.yml,
  # will take care of https and load balancing.
  anemowebapp_repl:
    image: anemomind/anemomind_anemowebapp:${TAG:-latest}
    volumes: 
      - "file-db:/db"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped
    environment:
      - PORT=9001
      - WAIT_HOSTS=anemomongo:27017
      - MONGOLAB_URI=mongodb://anemomongo/anemomind
      - JWT_SECRET=${JWT_SECRET:-NOT_SECURE_AT_ALL_123}
      - USE_GS=false  # store on filesystem
    
    links:
      - anemomongo
    depends_on:
      - anemomongo
      - anemocppserver
    labels:
      - traefik.enable=true
      - traefik.docker.network=anemolab_net
      - traefik.http.routers.anemowebapp_repl.rule=(Host(`anemolab.com`) || Host(`www.anemolab.com`)) && PathPrefix(`/api/{path:(map)|(tiles)|(export)}`)
      - traefik.http.routers.anemowebapp_repl.entrypoints=websecure
      - traefik.http.routers.anemowebapp_repl.tls.certresolver=le
      - traefik.http.services.anemowebapp_repl.loadbalancer.server.port=9001

  anemomongo:
    image: mongo:4.4.29
    container_name: anemomongo
    volumes:
      - "db-data:/data/db"
    #ports:
    #  - "27017:27017"
    networks:
      - back-tier
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 4

volumes:
    boat_logs:
    db-data:
    file-db:

networks:
  front-tier:
    external: true
    name: anemolab_net
  back-tier:
    attachable: true
