# Please refer the DockerREADME.md file 
# for the details regarding this docker-compose file

version: "3"

services:
  anemocppserver:
    image: gcr.io/${PROJECT_NAME}/anemomind_anemocppserver:${TAG}
    volumes:
      - "uploads:/uploads"
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
    
    links:
      - anemomongo
    depends_on:
      - anemomongo

  anemowebapp:
    image: gcr.io/${PROJECT_NAME}/anemomind_anemowebapp:${TAG}
    command: grunt serve:docker-dev --force
    ports:
      - "9000:9000"
    volumes: 
      - "uploads:/uploads"
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=anemomongo:27017
      - VHOST=client
    
    links:
      - anemomongo
    depends_on:
      - anemomongo
      - anemocppserver

  anemomongo:
    image: mvertes/alpine-mongo
    container_name: anemomongo
    volumes:
      - "db-data:/db/data"
    ports:
      - "27017:27017"
    networks:
      - back-tier
    restart: unless-stopped

volumes:
    shared_lib:
    shared_bin:        
    boat_logs:
    db-data:

networks:
  front-tier:
  back-tier:
