import os
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'HOME' : os.environ['HOME']})
Export('env')

# We should identify the platform here
# and provide appropriate flags.
env.AppendUnique(CPPPATH = ['/usr/local/include'])
env.AppendUnique(LIBPATH = ['/usr/local/lib'])
env.AppendUnique(CPPPATH = ['/usr/include'])
env.AppendUnique(LIBPATH = ['/usr/lib'])
env.AppendUnique(LIBS = ['armadillo', 'lapack_atlas'])
# env.AppendUnique(LIBS = ['ceres'])
env.AppendUnique(CPPFLAGS = ['-std=c++11'])

# adol-C
adolcbase = os.environ['HOME'] + '/adolc_base/';
env.AppendUnique(CPPPATH = [adolcbase + 'include'])
env.AppendUnique(LIBPATH = [adolcbase + 'lib64'])
env.AppendUnique(LIBS = ['adolc'])

# http://www.scons.org/doc/2.0.1/HTML/scons-user/x3444.html
VariantDir('build', 'src', duplicate = 0)

objs = SConscript('build/SConscript')

main = env.Program('build/main', objs)


