import os
import copy
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'HOME' : os.environ['HOME']})
Export('env')

# We should identify the platform here
# and provide appropriate flags.
env.AppendUnique(CPPPATH = ['/usr/local/include'])
env.AppendUnique(LIBPATH = ['/usr/local/lib'])
env.AppendUnique(CPPPATH = ['/usr/include'])
env.AppendUnique(LIBPATH = ['/usr/lib'])

# http://arma.sourceforge.net/
env.AppendUnique(LIBS = ['armadillo', 'lapack_atlas'])

# http://code.google.com/p/ceres-solver/
# env.AppendUnique(LIBS = ['ceres'])

env.AppendUnique(CPPFLAGS = ['-std=c++11'])

# ADOL-C: http://www.coin-or.org/projects/ADOL-C.xml
adolcbase = os.environ['HOME'] + '/adolc_base/';
env.AppendUnique(CPPPATH = [adolcbase + 'include'])
env.AppendUnique(LIBPATH = [adolcbase + 'lib64'])
env.AppendUnique(LIBS = ['adolc'])

# Put the object code in a different location than the source code.
# http://www.scons.org/doc/2.0.1/HTML/scons-user/x3444.html
VariantDir('build', 'src', duplicate = 0)


##################### MAIN PROGRAM #######################
main = env.Program('build/main', SConscript('build/SConscriptMain'))

##################### TESTING ############################
with_test    = 1		# Flag to build test
with_runtest = 1		# Flag to run tests

if with_test:
	gtestlibs = ['gtest', 'gtest_main']
	gtestlibpath = ['/usr/lib/gtest']    # a link to gtest-1.7.0/lib/.libs
	env.AppendUnique(LIBS = gtestlibs)
	env.AppendUnique(LIBPATH = gtestlibpath)
	test = env.Program('build/test', SConscript('build/SConscriptTest'))	

	if with_runtest:
		runtest = env.Command(target = "build/testlog.txt",
							  source = "build/test",
                			  action = ["build/test > $TARGET",
                			  			"cat $TARGET"])
		Depends(runtest, test)
		AlwaysBuild(runtest)
		