apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: anemocppserver
  name: anemocppserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: anemocppserver
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcs-key
      containers:
      - image: gcr.io/${PROJECT_NAME}/${CPP_DOCKER_IMAGE}
        name: anemocppserver
        securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
        lifecycle:
            postStart:
              exec:
                command: ["gcsfuse", "-o", "nonempty", "${BUCKET_NAME}", "/anemomind/boat_logs"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/anemomind/boat_logs"]
        resources: {}
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: MONGO_URL
          value: mongodb://main_admin:${MONGO_PWD}@mongod-0.mongodb-service:27017,mongod-1.mongodb-service:27017,mongod-2.mongodb-service:27017/anemomind-dev?replicaSet=MainRepSet&authSource=admin
      restartPolicy: Always
status: {}
