apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: esalabwebapp
  name: esalabwebapp
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  type: LoadBalancer
  selector:
    name: esalabwebapp
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: esalabwebapp
  name: esalabwebapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: esalabwebapp
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcs-key
      containers:
      - args:
        - grunt
        - serve:docker-dev
        - --force
        image: gcr.io/anemomind/esalabwebapp:latest
        name: esalabwebapp
        ports:
        - containerPort: 9000
        securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
        resources: {}
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: MONGO_URL
          value: mongodb://main_admin:anemo123@10.0.0.62:27017,10.0.0.61:27017,10.0.0.60:27017/anemomind-dev?replicaSet=MainRepSet&authSource=admin
        - name: LOAD_BIN_PATH
          value: /anemomind/bin/logimport_try_load
        - name: VHOST
          value: esalab
        - name: STRIPE_SECRET_KEY
          value: sk_test_VbBYlclpCZOdkawrD8e4X2nB 
      restartPolicy: Always
status: {}
