apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: anemowebapp
  name: anemowebapp
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  type: LoadBalancer
  selector:
    name: anemowebapp
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: anemowebapp
  name: anemowebapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: anemowebapp
    spec:
      containers:
      - args:
        - grunt
        - serve:docker-dev
        - --force
        image: ${WEB_DOCKER_IMAGE}
        name: anemowebapp
        ports:
        - containerPort: 9000
        resources: {}
        env:
        - name: MONGO_URL
          value: mongodb://main_admin:${MONGO_PWD}@mongod-0.mongodb-service:27017,mongod-1.mongodb-service:27017,mongod-2.mongodb-service:27017/anemomind-dev?replicaSet=MainRepSet&authSource=admin
      restartPolicy: Always
status: {}
