/*
 *  Created on: 2014-
 *      Author: Jonas Östlund <uppfinnarjonas@gmail.com>
 */

#ifndef DATASPLITS_H_
#define DATASPLITS_H_

#include <server/common/Array.h>
#include <random>

namespace sail {

Arrayb makeRandomSplit(int size, std::default_random_engine &e);
Array<Arrayb> makeRandomSplits(int numSplits, int size,
    std::default_random_engine &e);

// Make a split of few or many contiguous parts.
// prob next should be in the interval ]0, 1[
// and controls the number of parts.
Arrayb makeChunkSplit(int length,
    std::default_random_engine &e, double probNext = 0.7);

// Fills an array of elements generated by above function
Array<Arrayb> makeChunkSplits(int count, int length,
    std::default_random_engine &e, double probNext = 0.7);

}

#endif /* DATASPLITS_H_ */
